### ISSUE TITLE
`message_builder.h#message_builder_u` lost ability to contain a `set_solar_state_cmd_t`; should not have been lost

### ISSUE THREAD

**Issue by epicstar** [PlanetaryRobotics/moonranger-rover-messages#142]
**Describe the bug**

Whichever downstream software is using using `message_builder_u` may lose the ability to send a solar state command.

I tracked this change in #138, where it seems `message_builder.h#message_builder_u` lost `set_solar_state_cmd_t` but gained a `OBC_Set_Solar_Panel_Motor_Speed_Cmd_t`. I don't think MCS uses the union but I assume this will create a bug on the autonomy or other software sides.

I am not sure of the ramifications of this. However, it's good to note. Since @tanmayraj made the change, I assigned it to him.

I believe the fix is simple: just readd the line that was deleted (see code snips)

**To Reproduce**
N/A

**Expected behavior**
`set_solar_state_cmd_t` should not be removed, and `OBC_Set_Solar_Panel_Motor_Speed_Cmd_t` should only have been added to the struct.

**Code snips**

https://github.com/PlanetaryRobotics/moonranger-rover-messages/compare/3118f8902701b051e475263bfdba77abcde411f9...abc3825c6a5225c339eeb75276eaee784ca3f7e6#diff-f6e70108224950b0b5a3d46618d7293734be0e2c166a74f4731a0ec218c7ed4dL96

**System observed on:**
 - Local laptop
 - OS: Ubuntu 22.04
 - Versions: Mssion Control Software 7.1.0

**Reporter Info**

@epicstar (Jeremy Jao) from the Masters of Software Engineering program, working on Misison Control Software as his year-long capstone project.

**Comment by epicstar** [comment]
After discussion with @tenzincrouch and @tanmayraj, this is not an issue.

**Comment by tanmayraj** [comment]
`OBC_Set_Solar_Panel_State_Cmd_t Set_Solar_Panel_State_Cmd;` captures the missing type.
set_solar_state_cmd_t was duplicate with the same type listed and hence removed.

**Comment by epicstar** [comment]
Reopening and co-assigning @tenzincrouch just to ensure that everything was expected.
