### ISSUE TITLE
create Motor Controller message definitions

### ISSUE THREAD

**Issue by nehalchaturvedi** [PlanetaryRobotics/moonranger-rover-messages#53]

**Comment by mlang25** [comment]
See: https://docs.google.com/spreadsheets/d/1lnlChW43g_FARthIaxqzq6zdKIEjjN1nQwppoxDpViE/edit#gid=2136533811

Codified message structs are here: https://github.com/PlanetaryRobotics/moonranger-rover-messages/blob/main/fsw/public_inc/motor_controller_msgs.h
