### ISSUE TITLE
Review use of OS_Pack function

### ISSUE THREAD

**Issue by tenzincrouch** [PlanetaryRobotics/moonranger-rover-messages#74]
OS_Pack is used by a number of message functions. There is a question as to whether it is safe 
https://stackoverflow.com/questions/8568432/is-gccs-attribute-packed-pragma-pack-unsafe

Task: Review background material on OS_PACK and determine if suitable for our use cases?

Success criteria:
1-2 slide summary of research presented next week.

**Comment by abdallam1007** [comment]
Attached is a pdf of the summary done on the proposed question.
[Issue#74.pdf](https://github.com/PlanetaryRobotics/moonranger-rover-messages/files/8368102/Issue.74.pdf)
