### ISSUE TITLE
Update goal message for sending to rover

### ISSUE THREAD

**Issue by tenzincrouch** [PlanetaryRobotics/moonranger-rover-messages#77]
As per this PR - https://github.com/PlanetaryRobotics/moonranger-rover-messages/pull/76#pullrequestreview-890217093

There is a new flag in the goal message. 

Please add to the goal message from the ground station.

**Comment by ashwin21rao** [comment]
This has been raised as a PR in the MCS backend: https://github.com/PlanetaryRobotics/moonranger-ground-backend/pull/170
